{
 "title": "JWT Pizza",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "LOGS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP REQUESTS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"DELETE\"}[30s])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"GET\"}[30s])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"POST\"}[30s])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"PUT\"}[30s])",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[30s]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "average request latency"
    },
    {
     "expr": "rate(pizza_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizza latency"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACTIVE USERS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "last_over_time(users_total{source=\"jwt-pizza-service\"}[10s])",
     "legendFormat": "total active users"
    }
   ]
  },
  {
   "title": "AUTH ATTEMPTS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_fail_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "REVENUE/MINUTE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "revenue/minute"
    }
   ]
  },
  {
   "title": "PIZZA ORDERS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(ordered_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizzas ordered/minute"
    },
    {
     "expr": "rate(order_fail_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "failed orders/minute"
    }
   ]
  }
 ]
}